CREATE DATABASE HEALTH_INSURANCE_ANALYSIS;

USE HEALTH_INSURANCE_ANALYSIS


CREATE TABLE INSURANCE(
RECORD_ID INT IDENTITY(1,1) PRIMARY KEY,
AGE INT,
SEX VARCHAR(20),
BMI DECIMAL(5,2),
CHILDREN INT,
SMOKER VARCHAR(10),
REGION VARCHAR(20),
CHARGES DECIMAL(12,2),
LOADED_DATE DATETIME DEFAULT GETDATE()
);


SELECT * FROM INSURANCE_DATA;


SELECT COUNT(*) AS TOTAL_RECORDS FROM INSURANCE_DATA;

SELECT TOP 10 * FROM INSURANCE_DATA;

--AVERAGE COST PER CUSTOMER

SELECT
COUNT(*) AS TOTAL_CUSTOMERS,
CAST(AVG(CHARGES) AS DECIMAL(10,2)) AS AVG_ANNUAL_COST,
CAST(MIN(CHARGES) AS DECIMAL(10,2)) AS LOWEST_COST,
CAST(MAX(CHARGES) AS DECIMAL(10,2)) AS HIGHEST_COST,
CAST(SUM(CHARGES) AS DECIMAL(10,2)) AS TOTAL_ANNUAL_CLAIMS,
SUM(CASE WHEN CHARGES>20000 THEN 1 ELSE 0 END) AS HIGH_COST_CUSTOMERS,
CAST(SUM(CASE WHEN CHARGES>20000 THEN 1 ELSE 0 END) * 100/ COUNT(*) AS DECIMAL(5,2)) AS HIGH_COST_PERCENTAGE
FROM INSURANCE_DATA;


--SMOKER ANALYSIS

SELECT
SMOKER,
COUNT(*) AS CUSTOMER_COUNT,
CAST(AVG(CHARGES) AS DECIMAL(10,2)) AS AVG_ANNUAL_COST,
CAST(SUM(CHARGES) AS DECIMAL(15,2)) AS TOTAL_CLAIMS,
CAST(COUNT(*) * 100 / (SELECT COUNT(*) FROM INSURANCE_DATA) AS DECIMAL(10,2)) AS PERCENTAGE_OF_CUSTOMERS,
CAST((AVG(CHARGES) / (SELECT AVG(CHARGES) FROM INSURANCE_DATA WHERE SMOKER='NO')-1) * 100 AS DECIMAL(5,2)) AS PERCENT_MORE_EXPENSIVE
FROM INSURANCE_DATA
GROUP BY SMOKER
ORDER BY AVG_ANNUAL_COST;


--BMI + SMOKING

SELECT
CASE 
    WHEN BMI < 18.5 THEN 'UNDER WEIGHT'
    WHEN BMI BETWEEN 18.5 AND 24.9 THEN 'NORMAL'
    WHEN BMI BETWEEN 25 AND 29.9 THEN 'OVER WEIGHT'
    ELSE 'OBESE'
END AS BMI_CATEGORY,
SMOKER,
COUNT(*) AS CUSTOMER_COUNT,
CAST(AVG(CHARGES) AS DECIMAL(10,2)) AS AVG_COST
FROM INSURANCE_DATA
GROUP BY CASE 
    WHEN BMI < 18.5 THEN 'UNDER WEIGHT'
    WHEN BMI BETWEEN 18.5 AND 24.9 THEN 'NORMAL'
    WHEN BMI BETWEEN 25 AND 29.9 THEN 'OVER WEIGHT'
    ELSE 'OBESE'
END,
SMOKER
ORDER BY AVG_COST desc;

--AGE-GROUPS


SELECT 
    CASE 
        WHEN Age < 25 THEN '18-24'
        WHEN Age BETWEEN 25 AND 35 THEN '25-35'
        WHEN Age BETWEEN 36 AND 50 THEN '36-50'
        ELSE '50+'
    END AS AgeGroup,
    COUNT(*) as CustomerCount,
    CAST(AVG(Charges) AS DECIMAL(10,2)) as AvgCost
FROM INSURANCE_DATA
GROUP BY 
    CASE 
        WHEN Age < 25 THEN '18-24'
        WHEN Age BETWEEN 25 AND 35 THEN '25-35'
        WHEN Age BETWEEN 36 AND 50 THEN '36-50'
        ELSE '50+'
    END
ORDER BY AvgCost;


--REGIONAL COST COMPARISION

SELECT
REGION,
COUNT(*) AS CUSTOMER_COUNT,
CAST(AVG(CHARGES) AS DECIMAL(10,2)) AS AVG_COST,
CAST(SUM(CHARGES) AS DECIMAL(10,2)) AS TOTAL_CLAIMS,
CAST(AVG(AGE) AS DECIMAL(5,1)) AS AVG_AGE,
CAST(AVG(BMI) AS DECIMAL(5,2)) AS AVG_BMI,
SUM(CASE WHEN SMOKER='YES' THEN 1 ELSE 0 END) AS SMOKER_COUNT,
CAST(SUM(CASE WHEN SMOKER='YES' THEN 1 ELSE 0 END)*100 / COUNT(*) AS DECIMAL(5,2)) AS SMOKE_RATE,
CAST((AVG(CHARGES) / (SELECT AVG(CHARGES) FROM INSURANCE_DATA) - 1) * 100 AS DECIMAL(5,1)) as PERCENTAGEDIFFFROMNATIONAL
FROM INSURANCE_DATA
GROUP BY REGION 
ORDER BY AVG_COST DESC;

--FAMILY SIZE IMPACT

SELECT
CHILDREN,
COUNT(*) AS CUSTOMER_COUNT,
CAST(AVG(CHARGES) AS DECIMAL(10,2)) AS AVG_COST,
CAST(AVG(AGE) AS DECIMAL(5,2)) AS AVG_PARENT_AGE,
SUM(CASE WHEN SMOKER='YES' THEN 1 ELSE 0 END) AS SMOKER_COUNT,
CAST(AVG(CHARGES) - LAG(AVG(CHARGES)) OVER (ORDER BY CHILDREN) AS DECIMAL(10,2)) as INCREMENTALCOSTPERCHILD
FROM INSURANCE_DATA
GROUP BY CHILDREN 
ORDER BY CHILDREN

--HIGH RISK CUSTOMER DETAILED PROFILE

SELECT TOP 50
    AGE,
    SEX,
    BMI,
    CHILDREN,
    SMOKER,
    REGION,
    CHARGES,
CASE 
        WHEN BMI >= 30 AND SMOKER = 'YES' THEN 'CRITICAL RISK'
        WHEN BMI >= 30 OR Smoker = 'YES' THEN 'HIGH RISK'
        WHEN BMI >= 25 THEN 'MEDIUM RISK'
        ELSE 'LOW RISK'
    END AS RISK_CATEGORY,
CAST(CHARGES - (SELECT AVG(CHARGES) FROM INSURANCE_DATA) AS DECIMAL(10,2)) as EXCESS_COST,
CAST(CHARGES - (SELECT AVG(CHARGES) FROM INSURANCE_DATA WHERE BMI < 25 AND SMOKER = 'NO') AS DECIMAL(10,2)) as POTENTIAL_SAVINGS_IF_HEALTHY
FROM INSURANCE_DATA
ORDER BY CHARGES DESC;

CREATE VIEW vw_CustomerRiskProfile AS
SELECT 
    Age,
    Sex,
    BMI,
    Children,
    Smoker,
    Region,
    Charges,
    
    -- Calculated Risk Categories
    CASE 
        WHEN Age < 25 THEN '18-24'
        WHEN Age BETWEEN 25 AND 35 THEN '25-35'
        WHEN Age BETWEEN 36 AND 50 THEN '36-50'
        ELSE '50+'
    END AS AgeGroup,
    
    CASE 
        WHEN BMI < 18.5 THEN 'Underweight'
        WHEN BMI BETWEEN 18.5 AND 24.9 THEN 'Normal Weight'
        WHEN BMI BETWEEN 25 AND 29.9 THEN 'Overweight'
        ELSE 'Obese'
    END AS BMI_Category,
    
    CASE 
        WHEN BMI >= 30 AND Smoker = 'yes' THEN 'Critical Risk'
        WHEN BMI >= 30 OR Smoker = 'yes' THEN 'High Risk'
        WHEN BMI >= 25 THEN 'Medium Risk'
        ELSE 'Low Risk'
    END AS RiskCategory,
    
    CASE 
        WHEN Charges > 20000 THEN 'High Cost'
        WHEN Charges > 10000 THEN 'Medium Cost'
        ELSE 'Low Cost'
    END AS CostSegment,
    
    -- Calculated Metrics
    CAST(Charges / 12 AS DECIMAL(10,2)) AS MonthlyCost
    
FROM INSURANCE_DATA;
GO

-- ============================================
-- VIEW 2: Regional Summary
-- Aggregated metrics by region
-- ============================================

CREATE VIEW vw_RegionalSummary AS
SELECT 
    Region,
    COUNT(*) as CustomerCount,
    CAST(AVG(Charges) AS DECIMAL(10,2)) as AvgCost,
    CAST(SUM(Charges) AS DECIMAL(15,2)) as TotalClaims,
    CAST(AVG(Age) AS DECIMAL(5,1)) as AvgAge,
    CAST(AVG(BMI) AS DECIMAL(5,2)) as AvgBMI,
    SUM(CASE WHEN Smoker = 'yes' THEN 1 ELSE 0 END) as SmokersCount,
    CAST(SUM(CASE WHEN Smoker = 'yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS DECIMAL(5,2)) as SmokerRate
FROM INSURANCE_DATA
GROUP BY Region;


SELECT * FROM vw_CustomerRiskProfile;


SELECT 
    TABLE_SCHEMA,
    TABLE_NAME
FROM INFORMATION_SCHEMA.VIEWS
WHERE TABLE_CATALOG = 'Health_Insurance_Analysis';